export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SET_MESSAGE = "SET_MESSAGE";
export const LOGOUT = "LOGOUT";
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";

//CHAT ROOM
export const LOAD_CHAT_ROOM = "LOAD_CHAT_ROOM";
export const SET_CURRENT_ROOM = "SET_CURRENT_ROOM";
export const LOAD_ROOM_LIST = "LOAD_ROOM_LIST";
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const SET_ONLINE_USERS = 'SET_ONLINE_USERS';
export const LOAD_INVITATION_LIST = 'LOAD_INVITATION_LIST';
export const RECEIVE_INVITATION = 'RECEIVE_INVITATION';